### ISSUE TITLE
Convert to HTML

### ISSUE THREAD

**Issue by putuyuwono** [123jimin/node-hwp#15]
Hi,
I am looking for HWP converter. So far, your library has the closest proximity to HTML. Is there any plan to support HTML conversion?

**Comment by 12345data** [comment]
Is there any possibility to convert HWP to HTML now?

**Comment by 123jimin** [comment]
Sorry, I'm not actively developing this repo anymore.
I am willing to help on codes on this repo and how HWP v5 documents are structured, however.
